---
driver:
  name: vagrant
  ssh:
    insert_key: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
<% count = 9; %w(chef analytics supermarket).each do |name| %>
- name: <%= name %>-server
  run_list:
  - recipe[chef-provisioning::default]
  driver:
    vm_hostname: <%= name %>-server.example.com
    network:
      - ['private_network', {ip: '33.33.33.<%= count+=1 %>'}]
    customize:
      memory: 2048
      cpus: 2
  attributes:
<% end %>
